#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def find(limit):
    previous = 1
    current = 2
    tally = 0
    while(current < limit):
        if(current % 2 == 0):
            tally += current

        temp = current
        current += previous 
        previous = temp
    print(tally)
     
if __name__ == '__main__':
    find(4000000)       
             



